// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiBackend.Models;

public partial class SharedReminders
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public int? ReminderId { get; set; }
}